config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'users#splash'
  #root 'users#index'
  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end
  
  resources :users, only: [:splash]
  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy], :path => "categories" do 
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy], :path => "transactions"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless current_user.present? # logged in user only can access the app (not guest)

    can(:manage, Group, user:)
    can(:manage, Expense, user:)
    can :manage, GroupExpense do |category_transaction|
      category_transaction.group.user == user
    end

    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, length: { in: 1..50 },
                   uniqueness: { scope: :author, message: 'You already have an transaction with this name' }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 1..15 },
                   uniqueness: { scope: :author, message: 'You already have a category with this name' }
  validates :icon, presence: true, length: { in: 1..150 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  def total_transactions
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { in: 1..15 }
  validates :email, presence: true, length: { in: 1..50 }, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }

  has_many :groups, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:splash]
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_url
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[edit update destroy]
  before_action :set_group, only: %i[index new edit create update destroy]
  before_action :set_user, only: %i[index edit create update destroy]
  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET group/expenses/new
  def new
    @expense = Expense.new
  end

  # GET group/expenses/1/edit
  def edit; end

  # POST group/expenses
  def create
    @expense = Expense.new(author: @author, **expense_params)
    if @expense.save
      @group_expense = GroupExpense.create(group: @group, expense: @expense)
      redirect_to group_expenses_url(@group), notice: 'Expense was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT group/expenses/1
  def update
    if @expense.update(expense_params)
      redirect_to group_expenses_url, notice: 'Expense was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE group/expenses/1
  def destroy
    @expense.destroy
    redirect_to group_expenses_url(@group), notice: 'Expense was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @author = current_user
  end

  def set_group
    @group = set_user.groups.find(params[:group_id])
  end

  def set_expense
    @expense = set_user.expenses.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[edit update destroy]
  before_action :set_user, only: %i[index edit create update destroy]

  # GET /groups or /groups.json
  def index
    @groups = @author.groups
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(author: @author, **group_params)

    if @group.save
      redirect_to groups_url, notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    if @group.update(group_params)
      redirect_to groups_url, notice: 'Group was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @author = current_user
  end

  def set_group
    @group = set_user.groups.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :redirect_to_categories, only: %i[show index]
  # Splash page for unauthenticated users (see app/controllers/application_controller.rb)
  def splash
    if current_user
      redirect_to groups_url, alert: "You are already logged in as, #{current_user.name}"
    else
      render :splash
    end
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def redirect_to_categories
    redirect_to groups_url
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="my-5 flex items-center justify-between">
  <div class="flex items-center gap-3">
    <div class="flex items-center gap-2">
      <%= image_tag @group.icon, class: "rounded-full w-20 h-20 object-cover" %>
      <%= expense.name %>
      <span class="font-bold">$<%= expense.amount %> </span>
    </div>
  </div>
  <% if action_name != "show" %>
    <div class="flex gap-2">
    <%= link_to edit_group_expense_path(@group,expense), class: "rounded-lg py-1 px-1 bg-gray-100 inline-block font-medium" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-amber-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    <% end %>
    <%= button_to group_expense_path(@group, expense), method: :delete, class: "rounded-lg py-1 px-1 bg-gray-100 inline-block font-medium" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-red-500">
       <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
      </svg>
    <% end %>
    </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? group_expense_path(@group, expense) : group_expenses_path(@group)}", class: "contents") do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: ".01", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="mt-10 bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "w-[80%] py-2 px-5 bg-second border text-white block uppercase font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<% content_for :title, 'Carpe Diem | Transactions' %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing expense</h1>

  <%= render "form", expense: @expense %>

  <%= link_to "Back to expenses", group_expenses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/expenses/index.html.erb
<% content_for :title, "Carpe Diem | #{@group.name} Transactions" %>
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= "#{@group.name}' " %>Transactions</h1>
  </div>

  <!--max-h-[320px] overflow-y-scroll -->
  <div id="expenses" class="min-w-full">
    <%= render @expenses %>
  </div>
</div>

<div class="bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center">
  <%= link_to new_group_expense_path, class: "w-[80%] flex items-center justify-center gap-2 py-2 px-5 bg-second border text-white block font-medium" do %>
    <span>New transaction</span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
    </svg>
  <% end %>
</div>

app/views/expenses/new.html.erb
<% content_for :title, 'Carpe Diem | New Transaction' %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Transaction</h1>

  <%= render "form", expense: @expense %>
  
  <%= link_to 'Back to expenses', group_expenses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :icon %>
    <%= form.text_field :icon, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
  </div>

  <div class="mt-10 bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "w-[80%] py-2 px-5 bg-second border text-white block uppercase font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="my-5 flex items-center justify-between">
  <div class="flex items-center gap-3">
    <%= link_to  group_expenses_path(group), class: "flex items-center gap-3" do %>
      <%= image_tag group.icon, class: "rounded-full w-20 h-20 object-cover" %>
      <span> <%= group.name %> </span>
      <span class="font-bold"> $<%= group.total_transactions %> </span>
    <% end %>
  </div>
  <% if action_name != "show" %>
    <div class="flex gap-2">
    <%= link_to edit_group_path(group), class: "rounded-lg py-1 px-1 bg-gray-100 inline-block font-medium" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-amber-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    <% end %>
    <%= button_to group_path(group), method: :delete, class: "rounded-lg py-1 px-1 bg-gray-100 inline-block font-medium" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-red-500">
       <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
      </svg>
    <% end %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<% content_for :title, 'Carpe Diem | Categories' %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing <%=@group.name %></h1>

  <%= render "form", group: @group %>

  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<% content_for :title, 'Carpe Diem | Categories' %>
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl font-sans">Categories</h1>
  </div>

  <div id="groups" class="min-w-full">
    <%= render @groups %>
  </div>
  
</div>
<div class="bg-second fixed bottom-0 left-0 right-0 py-3 flex justify-center">
  <%= link_to new_group_path, class: "w-[80%] flex items-center justify-center gap-2 py-2 px-5 bg-second border text-white block font-medium" do %>
    <span> <%= 'New Category' %> </span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 7.125C2.25 6.504 2.754 6 3.375 6h6c.621 0 1.125.504 1.125 1.125v3.75c0 .621-.504 1.125-1.125 1.125h-6a1.125 1.125 0 01-1.125-1.125v-3.75zM14.25 8.625c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v8.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-8.25zM3.75 16.125c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v2.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-2.25z" /> 
    </svg>
  <% end %>
</div>

app/views/groups/new.html.erb
<% content_for :title, 'Carpe Diem | New Category' %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Category</h1>

  <%= render "form", group: @group %>

  <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/_nav.html.erb
<nav class="fixed mb-5 px-3 top-0 right-0 left-0 bg-main pt-5 z-50">
  <div class="top-nav flex items-center justify-between border-b-2 pb-2">
      <% if controller_name == 'groups' and action_name == 'index' %>
        <div class="hamburger-menu">
          <svg class="stroke-white h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </div>
      <% elsif controller_name == 'groups' and action_name != 'index' %>
        <div class="back-btn">
          <%= link_to groups_path do %>
          <svg class="stroke-white h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
          </svg>
          <% end %>
        </div>
      <% elsif controller_name == 'expenses' %>
        <div class="back-btn">
          <%= link_to "#{action_name == 'index' ? groups_path : group_expenses_path}" do %>
          <svg class="stroke-white h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
          </svg>
          <% end %>
        </div>
      <% end %>
      <h1 class="text-white text-2xl m-0 uppercase">
        <% if controller_name == 'expenses' %>
          <%= 'Transactions' %>
        <% else %>
          <%= 'Categories' %>
        <% end %>
      </h1>
      <div class="search">
        <svg class="h-8 w-8 stroke-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>
      </div>
  </div>
  <div class="my-3 flex justify-between">
    <span class="bg-white py-1 px-2 w-max rounded-lg text-main font-semibold">
      <%= current_user.name %>
      <% if controller_name == 'expenses' %>
        : $<%= @group.total_transactions %>
      <% end %>
    </span>
    <%= button_to destroy_user_session_path, method: :delete, class: 'flex items-center gap-2' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8 stroke-white">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
      </svg>
      <span class="text-white font-semibold">Log Out</span>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% elsif alert.present? %>
       <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
      <% end %>

      <% if current_user %>
        <%= render 'layouts/nav' %>
      <% end %>
      
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/splash.html.erb
<% content_for :title, 'Carpe Diem' %>
<div class="absolute top-8 flex items-center">
  <%= image_tag 'https://em-content.zobj.net/source/microsoft-teams/337/grinning-face_1f600.png', class: 'h-10 w-10' %>
</div>
<%= image_tag "carpe-diem-logo.png", class: 'md:max-w-md self-center' %>

<div class="actions absolute bottom-4 w-10/12 self-center">
  <%= link_to new_user_session_path, class: 'group rounded-lg mb-4 flex items-center bg-main p-3 justify-center border hover:border-main hover:bg-transparent' do %>
    <span class="group-hover:text-main text-white uppercase font-semibold">Log In</span>
  <% end %>
  <%= link_to new_user_registration_path, class: 'group rounded-lg flex items-center bg-main p-3 justify-center border hover:border-main hover:bg-transparent' do %>
    <span class="group-hover:text-main text-white uppercase font-semibold">Register</span>
  <% end %>
</div>